// @ontology
// system: build-version
// description: Build version stamp — generated by scripts/bump-sw-version.sh
// provides:
//   - window.BUILD_VERSION (displayed in title-screen footer)
// rules:
//   - generated file: do not edit manually (code: scripts/bump-sw-version.sh updates the version line)
// consumes: (none)
/* Build version — stamped by scripts/bump-sw-version.sh on every player-facing commit.
   Displayed in the title-screen footer so we always know which build is running. */
window.BUILD_VERSION = '7f16cb7-20261007-151941';
