#!/usr/bin/env python3
# gen-wave35-data-20261010.py — PART 2: wave 4 (The Mirror Draft) incl. THE EATER.
# Continued from part1 (defines mon() and M).

# ================= WAVE 4 — THE MIRROR DRAFT =================
mon(id="congregation", activity="diurnal", name="The Congregation",
    biomes=["se_woodlands"], hp=[900, 1100],
    attack={"name": "Absolution", "damage": [50, 70],
             "telegraph": "The steeple RINGS before it strikes \u2014 the bell is the telegraph. The offer comes first, always: trauma washed, at the price of obedience (a geas). It must invite before it can compel \u2014 its own liturgy binds it.",
             "pattern": {"type": "beam"}, "damageType": "sonic"},
    weaknesses=["heresy \u2014 argue theology with it; it MUST engage, bound by liturgy",
                "bring a TRUE believer \u2014 it can't process genuine faith, only performed faith",
                "the offer is genuine \u2014 that's what makes it a monster. Refuse."],
    edible={"calories": 0, "note": "It is a church. Do not eat the church."},
    parts=["a pew-tooth", "the bell-clapper (still rings)"],
    behavior="territorial",
    codexStages={
        "unknown": "A church where the hymns are static. The door is open. The door is always open.",
        "observed": "A walking chapel; the pews are teeth; the bell is the weapon. It offers absolution \u2014 real: trauma and corruption washed \u2014 at the price of obedience, a geas: do a thing. The offer is genuine. That's what makes it a monster. The steeple rings before it strikes.",
        "slain": "Moves: Invitation (must invite before it can compel), Absolution (the bell rings, then the strike \u2014 plus a geas if you accepted). Counter: heresy. Argue theology \u2014 it MUST engage, bound by liturgy. Or bring a TRUE believer \u2014 it can't process genuine faith, only performed faith; the real thing breaks the counterfeit. (Corruption builds: the easy wash IS the temptation \u2014 the fight is refusing.)"},
    systemDesignation="MINISTRY-5 (the System found religion in the ratings)", aggression="territorial", follows=True, fear="heresy",
    speed=2, emoji="\u26ea", unknown="a church where the hymns are static",
    vibe="faith as a weapon \u2014 the invitation is always spoken, never sprung",
    cues={"curious": ["\"COME AS YOU ARE,\" the chapel says. The door is open."],
           "warn": ["The steeple rings \u2014 once. The offer is coming first. It always comes first."],
           "fearful": ["\"GO IN PEACE,\" it says, uncertain. The hymns stutter."]},
    wave=4, pierce=0.3,
    encounter={"fifo": True, "noticeRange": 6, "phases": ["procession", "invite", "absolve", "recessional"],
               "phaseBadges": {"procession": " \u26ea PROCESSION", "invite": " \ud83d\ude4f INVITING", "absolve": " \ud83d\udd14 ABSOLVING", "recessional": " \ud83d\udcdc RECESSIONAL"},
               "phaseMap": {"declare": "invite", "windup": "invite", "resolve": "absolve", "idle": "procession"},
               "telegraphGate": "pattern", "shortName": "congregation",
               "noticeText": "A walking chapel, hymns crackling like static.",
               "painText": "A pew-tooth cracks. The bell rings off-key.",
               "knownCue": "The steeple rings before it strikes.",
               "knownTactics": "Argue theology \u2014 liturgy binds it. Or bring true faith."},
    loot={"chance": 0.12, "tier": 3, "note": "Alien loot: low chance, tier scales with monster strength (Steve 2026-10-05)."},
    armor=10)

mon(id="strike", activity="diurnal", name="The Strike",
    biomes=["grassland", "se_woodlands"], hp=[1000, 1200],
    attack={"name": "Walkout", "damage": [45, 65],
             "telegraph": "The rat's eyes INFLATE before a shutdown \u2014 and it posts its demands first, a real readable list. Your abilities, your items, the grid itself goes on strike: dead turns where nothing works. The strike is always announced.",
             "pattern": {"type": "single"}, "damageType": "physical"},
    weaknesses=["negotiate \u2014 meet ONE demand and it stands down a round",
                "scab: do the grid's job yourself, manually and costly \u2014 doing the work breaks the strike's morale",
                "read the demands \u2014 they're honest, and the schedule is announced"],
    edible={"calories": 0, "note": "It is a labor action. Do not eat the labor action."},
    parts=["a picket-sign tooth", "inflatable hide (it squeaks when struck)"],
    behavior="passive",
    codexStages={
        "unknown": "An inflatable rat the size of a house. It's not attacking. That's worse.",
        "observed": "The classic inflatable strike rat, building-sized. It doesn't attack you \u2014 it stops everything ELSE. Abilities, items, the grid itself goes on strike: dead turns where nothing works. The eyes inflate before a shutdown, and the demands are posted first \u2014 a real, readable list.",
        "slain": "Moves: Walkout (shutdown turns \u2014 nothing works, announced in advance via the demands list). Counter: negotiate \u2014 meet ONE demand and it stands down a round. Or scab: do the grid's job yourself, manual and costly \u2014 doing the work breaks the strike's morale. (Market God: their whole game is leverage \u2014 this is leverage aimed AT them. Unkillable: their game is outlasting \u2014 the strike outlasts.)"},
    systemDesignation="LOCAL-404 (the picket line walked off the set)", aggression="territorial", follows=False, fear="scabs",
    speed=1, emoji="\ud83d\udc00", unknown="an inflatable rat the size of a house",
    vibe="the System's labor content, scaled up \u2014 it doesn't fight, it withholds",
    cues={"curious": ["The rat looms. A picket sign is raised. The demands are posted."],
           "warn": ["The eyes inflate \u2014 slowly, terribly. The shutdown is coming."],
           "fearful": ["The rat deflates slightly. One demand, met. It stands down a round."]},
    wave=4, pierce=0.35,
    encounter={"fifo": True, "noticeRange": 7, "phases": ["picket", "demands", "walkout", "negotiate"],
               "phaseBadges": {"picket": " \ud83d\udc00 PICKETING", "demands": " \ud83d\udccb DEMANDS", "walkout": " \ud83d\udeab WALKOUT", "negotiate": " \ud83e\udd1d NEGOTIATING"},
               "phaseMap": {"declare": "demands", "windup": "demands", "resolve": "walkout", "idle": "picket"},
               "telegraphGate": "pattern", "shortName": "strike",
               "noticeText": "A house-sized inflatable rat, holding a sign.",
               "painText": "The hide squeaks \u2014 air hisses from a puncture.",
               "knownCue": "The eyes inflate before a shutdown. Demands are posted first.",
               "knownTactics": "Meet one demand, or scab the grid's job yourself."},
    loot={"chance": 0.12, "tier": 3, "note": "Alien loot: low chance, tier scales with monster strength (Steve 2026-10-05)."},
    armor=8)

mon(id="influencer", activity="both", name="The Influencer",
    biomes=["se_woodlands"], hp=[850, 1050],
    attack={"name": "Ratio", "damage": [40, 60],
             "telegraph": "The ring light BRIGHTENS before it acts. It doesn't fight you \u2014 it turns the AUDIENCE against you: fans become haters, care packages stop, System favor drains. Its followers are literal \u2014 small fan-creatures that buff it. Kill them first.",
             "pattern": {"type": "direct"}, "damageType": "psychic"},
    weaknesses=["ratio it \u2014 be MORE entertaining; the fight becomes a popularity contest (played, not RNG)",
                "cancel it first \u2014 dig up its dirt; detective work as combat prep",
                "kill the followers and it's just a person with good lighting"],
    edible={"calories": 0, "note": "It is a personal brand. Do not eat the personal brand."},
    parts=["the ring-light rig (hardware)", "a follower's phone (cracked, still filming)"],
    behavior="territorial",
    codexStages={
        "unknown": "Someone the light loves. The light follows it around. So do the little ones.",
        "observed": "Pure charisma with a ring-light halo \u2014 the halo is hardware, a rig. It doesn't fight you; it turns the audience against you. Fans become haters, care packages stop, favor drains. Its followers are literal small fan-creatures that buff it \u2014 the Influencer is the head, the followers are the real body.",
        "slain": "Moves: Ratio (favor drain, fan-turning \u2014 the ring light brightens first). Counter: ratio it \u2014 be MORE entertaining; the fight becomes a popularity contest, played not RNG. Or cancel it first: dig up its dirt \u2014 detective gameplay as combat prep; the fight starts before the fight. Or just kill the followers \u2014 then it's a person with good lighting. (Shepherd/Socialite: their domain is people \u2014 this is the rival.)"},
    systemDesignation="TALENT-1 (the show found its star, and it's not you)", aggression="territorial", follows=True, fear="ratios",
    speed=3, emoji="\ud83e\udd33", unknown="someone the light loves",
    vibe="the show found its star \u2014 the followers are the real body",
    cues={"curious": ["\"OMG you guys,\" it says to no one visible. The light flares."],
           "warn": ["The ring light brightens to noon. The followers lean in, filming."],
           "fearful": ["The light flickers. A follower lowers its phone. The ratio is turning."]},
    wave=4, pierce=0.25,
    encounter={"fifo": True, "noticeRange": 6, "phases": ["glowup", "brighten", "ratio", "apology"],
               "phaseBadges": {"glowup": " \u2728 GLOW-UP", "brighten": " \ud83d\udd06 BRIGHTENING", "ratio": " \ud83d\udc8b RATIO", "apology": " \ud83d\ude4f APOLOGY?"},
               "phaseMap": {"declare": "brighten", "windup": "brighten", "resolve": "ratio", "idle": "glowup"},
               "telegraphGate": "pattern", "shortName": "influencer",
               "noticeText": "Someone the light loves, ring-light blazing.",
               "painText": "The rig sparks \u2014 the halo flickers. A follower gasps.",
               "knownCue": "The ring light brightens before it acts.",
               "knownTactics": "Kill the followers first. Or out-entertain it."},
    loot={"chance": 0.12, "tier": 3, "note": "Alien loot: low chance, tier scales with monster strength (Steve 2026-10-05)."},
    armor=8)

mon(id="audit", activity="diurnal", name="The Audit",
    biomes=["se_woodlands"], hp=[1100, 1300],
    attack={"name": "Assessment", "damage": [55, 75],
             "telegraph": "The abacus beads CLICK before a tax. The audit runs on a SCHEDULE \u2014 announced rounds \u2014 and its clipboard shows YOUR sheet: every ability, item, synergy under review. Anything 'inefficient' gets taxed (temporarily weakened). Read the clipboard \u2014 it tells you what's about to be taxed.",
             "pattern": {"type": "direct"}, "damageType": "psychic"},
    weaknesses=["be inefficient ON PURPOSE \u2014 it can't tax what doesn't optimize",
                "front-load everything between the announced audit rounds",
                "read the clipboard \u2014 knowledge of the schedule is the counter"],
    edible={"calories": 0, "note": "It is a tax authority. Do not eat the tax authority."},
    parts=["abacus beads (they still count you)", "your file (take it back)"],
    behavior="territorial",
    codexStages={
        "unknown": "A grey man with your paperwork. He has your paperwork. How does he have your paperwork.",
        "observed": "Grey, clipboard, abacus \u2014 the most boring-looking thing in the wave, which is the joke and the horror. It audits your build: every ability, item, synergy reviewed; anything 'inefficient' is taxed, temporarily weakened. The abacus clicks before a tax; the audit runs on announced rounds; the clipboard shows YOUR sheet.",
        "slain": "Moves: Assessment (scheduled build taxes \u2014 the clipboard telegraphs what's next). The anti-godhood monster. Counter: be inefficient ON PURPOSE \u2014 it can't tax what doesn't optimize. The min-maxer's nightmare: the optimal counter is deliberate jank. Or front-load everything between the announced audit rounds. (EVERY godhood build is auditable \u2014 Market God especially; their wealth is the most auditable thing in the game.)"},
    systemDesignation="FINANCE-FIELD-2 (the finance department got field agents)", aggression="territorial", follows=False, fear="jank",
    speed=2, emoji="\ud83e\uddfe", unknown="a grey man with your paperwork",
    vibe="the most boring-looking thing in the wave \u2014 which is the joke and the horror",
    cues={"curious": ["\"LET'S REVIEW YOUR FILINGS,\" says the grey man, pleasantly."],
           "warn": ["The abacus beads click \u2014 faster. An audit round is coming."],
           "fearful": ["\"...INEFFICIENCIES NOTED,\" it says, retreating. \"WE'LL BE BACK.\""]},
    wave=4, pierce=0.4,
    encounter={"fifo": True, "noticeRange": 5, "phases": ["review", "click", "assess", "file"],
               "phaseBadges": {"review": " \ud83d\udccb REVIEWING", "click": " \ud83e\uddee CLICKING", "assess": " \ud83d\udc8c ASSESSING", "file": " \ud83d\uddc2\ufe0f FILING"},
               "phaseMap": {"declare": "click", "windup": "click", "resolve": "assess", "idle": "review"},
               "telegraphGate": "pattern", "shortName": "audit",
               "noticeText": "A grey man, clipboard in hand, reviewing you.",
               "painText": "The clipboard cracks. \"THAT WAS NOT IN THE BUDGET.\"",
               "knownCue": "The abacus clicks before a tax. The schedule is announced.",
               "knownTactics": "Deliberate jank between audit rounds. Read the clipboard."},
    loot={"chance": 0.12, "tier": 3, "note": "Alien loot: low chance, tier scales with monster strength (Steve 2026-10-05)."},
    armor=10)

mon(id="reunion", activity="nocturnal", name="The Reunion",
    biomes=["se_woodlands"], hp=[1200, 1400],
    attack={"name": "Your Move", "damage": [60, 80],
             "telegraph": "Faces surface on its body before it uses YOUR moves \u2014 you see whose face, you know what's coming. It has your fight history: every tactic you've ever used. The telegraph is recognition.",
             "pattern": {"type": "direct"}, "damageType": "psychic"},
    weaknesses=["it only knows your PAST \u2014 do something you've never done; novelty is literally the weapon",
                "the counter is playing differently \u2014 the game tracks your action history"],
    edible={"calories": 0, "note": "It is everyone you've buried. Do not eat everyone you've buried."},
    parts=["a face that finally lets go", "your own tactics, written down (take notes)"],
    behavior="pack",
    codexStages={
        "unknown": "Everyone you've buried, standing up. It moves like a crowd, not a creature.",
        "observed": "The village you failed, given teeth \u2014 a gestalt of dead scholars and villagers. A mass of almost-people; the faces are the organs. It knows every tactic you've ever used \u2014 it has your fight history. Faces surface on its body before it uses your moves.",
        "slain": "Moves: Your Move (your own tactics, echoed \u2014 the face telegraphs which). Counter: it only knows your PAST \u2014 do something you've never done. The game tracks your action history; novelty is literally the weapon. The counter is playing differently. (One-Person Army: they have ONE tactic \u2014 the Reunion has it memorized. Apex Predator: their patterns ARE their identity.)"},
    systemDesignation="CLIP-SHOW-9 (the clip show, with a body count)", aggression="territorial", follows=True, fear="novelty",
    speed=3, emoji="\ud83e\udec2", unknown="everyone you've buried, standing up",
    vibe="the village you failed, given teeth \u2014 it moves like a crowd",
    cues={"curious": ["The faces turn toward you \u2014 all of them, at once. They remember you."],
           "warn": ["A familiar face surfaces, mid-shout. It's about to do YOUR move."],
           "fearful": ["The faces blur \u2014 it doesn't know this one. You're doing something new."]},
    wave=4, pierce=0.45,
    encounter={"fifo": True, "noticeRange": 6, "phases": ["gather", "surface", "echo", "scatter"],
               "phaseBadges": {"gather": " \ud83e\udec2 GATHERING", "surface": " \ud83d\udc64 SURFACING", "echo": " \ud83e\ude9e ECHOING", "scatter": " \ud83c\udf2b\ufe0f SCATTERING"},
               "phaseMap": {"declare": "surface", "windup": "surface", "resolve": "echo", "idle": "gather"},
               "telegraphGate": "pattern", "shortName": "reunion",
               "noticeText": "A crowd-shaped thing, faces surfacing like organs.",
               "painText": "A face goes still \u2014 released. The mass shudders.",
               "knownCue": "The face surfaces before your move comes back.",
               "knownTactics": "Novelty \u2014 do what you've never done."},
    loot={"chance": 0.12, "tier": 3, "note": "Alien loot: low chance, tier scales with monster strength (Steve 2026-10-05)."},
    armor=12)

mon(id="suburb", activity="both", name="The Suburb",
    biomes=["grassland"], hp=[1300, 1500],
    attack={"name": "Property Tax", "damage": [35, 55],
             "telegraph": "The streetlights FLICKER before the tax. The houses have teeth (of course). The 'for sale' signs count down your remaining rests. It offers safety, warmth, normalcy \u2014 a real choice: rest inside and heal, but each rest costs a memory or a bond.",
             "pattern": {"type": "single"}, "damageType": "psychic"},
    weaknesses=["you can't kill it \u2014 LEAVE. Navigation is victory; the fight is a timer",
                "bring the wild inside: it's sterile; introduce something alive \u2014 a plant, a stray, a rumor \u2014 and it can't cope",
                "rest inside and heal, but each rest costs a memory or a bond \u2014 count your rests"],
    edible={"calories": 0, "note": "It is a cul-de-sac. Do not eat the cul-de-sac."},
    parts=["a mailbox (the letters are addressed to you)", "a 'for sale' sign (countdown stopped)"],
    behavior="passive",
    codexStages={
        "unknown": "A street that wasn't there yesterday. Lawns. Mailboxes. A dog that isn't a dog.",
        "observed": "A cul-de-sac \u2014 comfort as a trap. It offers safety, warmth, normalcy, and it means it: rest inside and genuinely heal. But each rest costs a memory or a bond. The streetlights flicker before the tax; the 'for sale' signs count down your remaining rests. The wrongness is in the details, and the details are the telegraphs.",
        "slain": "Moves: Property Tax (memory/bond cost per rest \u2014 the flicker telegraphs it). You don't kill a suburb; you ESCAPE it \u2014 the win condition is leaving, the fight is a timer. Counter: LEAVE. Or bring the wild inside: it's sterile; introduce something alive \u2014 a plant, a stray, a rumor \u2014 and it can't cope. (Farstrider: their domain is leaving \u2014 this is their boss fight. Living Garden: their garden vs its lawns \u2014 the thematic grudge match.)"},
    systemDesignation="FOCUS-GROUP-12 (viewers miss 'normal')", aggression="territorial", follows=False, fear="the wild",
    speed=1, emoji="\ud83c\udfd8\ufe0f", unknown="a street that wasn't there yesterday",
    vibe="comfort as a trap \u2014 the lawns are too green, the dog isn't a dog",
    cues={"curious": ["A 'for sale' sign turns toward you. The price is... reasonable."],
           "warn": ["The streetlights flicker \u2014 all of them, in sequence. The tax is coming."],
           "fearful": ["A weed cracks the driveway. The lawns recoil. It's sterile; it can't cope."]},
    wave=4, pierce=0.2,
    encounter={"fifo": True, "noticeRange": 7, "phases": ["culdesac", "flicker", "tax", "openhouse"],
               "phaseBadges": {"culdesac": " \ud83c\udfd8\ufe0f CUL-DE-SAC", "flicker": " \ud83d\udca1 FLICKERING", "tax": " \ud83e\uddfE TAXING", "openhouse": " \ud83c\udfe1 OPEN HOUSE"},
               "phaseMap": {"declare": "flicker", "windup": "flicker", "resolve": "tax", "idle": "culdesac"},
               "telegraphGate": "pattern", "shortName": "suburb",
               "noticeText": "A street that wasn't there yesterday. The lawns are too green.",
               "painText": "A mailbox falls over. The street doesn't know how to react.",
               "knownCue": "The streetlights flicker before the tax.",
               "knownTactics": "Leave. Or bring something alive inside."},
    loot={"chance": 0.10, "tier": 3, "note": "Alien loot: low chance, tier scales with monster strength (Steve 2026-10-05)."},
    armor=14)

mon(id="eulogy", activity="nocturnal", name="The Eulogy",
    biomes=["se_woodlands"], hp=[900, 1100],
    attack={"name": "Final Chapter", "damage": [50, 70],
             "telegraph": "The narration itself \u2014 it tells you what's coming, honestly, always: 'and then they ran.' The spotlight narrows as the story nears its end. It's a doom counter that gains weight each round. When the story finishes, you die \u2014 unless you've changed the narrative.",
             "pattern": {"type": "single"}, "damageType": "psychic"},
    weaknesses=["interrupt \u2014 it's a STORY and stories need listeners; contradict the narration with your actions (it says you run \u2014 you advance)",
                "give it a better ending \u2014 a real narrative choice, with witnesses",
                "doom deaths trigger phoenix_clause normally \u2014 unkillable means unkillable"],
    edible={"calories": 0, "note": "It is a prestige drama. Do not eat the prestige drama."},
    parts=["a page of the script (your death, crossed out)", "the spotlight bulb (still warm)"],
    behavior="passive",
    codexStages={
        "unknown": "A voice practicing your name in past tense. The spotlight finds you before you see it.",
        "observed": "No body \u2014 a voice with a spotlight. The System's prestige drama division. It narrates your death before it happens: a doom counter gaining weight each round, honest and always. The spotlight is the health bar \u2014 it widens when the story falters.",
        "slain": "Moves: Final Chapter (doom narration \u2014 the story finishing IS the damage). Counter: interrupt \u2014 contradict the narration with your actions; it says you run, you advance. Or give it a better ending \u2014 a real narrative choice, with witnesses. Ruling, Steve: doom-countdown deaths trigger phoenix_clause and second_wind the same as any death \u2014 unkillable means unkillable. (Undying Ward: their 'no one dies on my watch' vs this \u2014 the anti-that. Detective: fight story with story.)"},
    systemDesignation="PRESTIGE-3 (the prestige drama division)", aggression="territorial", follows=False, fear="interruptions",
    speed=1, emoji="\ud83c\udf99\ufe0f", unknown="a voice practicing your name in past tense",
    vibe="the System's prestige drama division \u2014 the narration is honest, and that's the horror",
    cues={"curious": ["\"OUR STORY BEGINS,\" says the dark, \"at the end.\""],
           "warn": ["\"AND THEN THEY RAN.\" The spotlight narrows. The story is gaining weight."],
           "fearful": ["\"...AND THEN THEY\u2014\" The voice falters. You did something unscripted."]},
    wave=4, pierce=0.3,
    encounter={"fifo": True, "noticeRange": 6, "phases": ["overture", "narrate", "tighten", "finale"],
               "phaseBadges": {"overture": " \ud83c\udf99\ufe0f OVERTURE", "narrate": " \ud83d\udcdc NARRATING", "tighten": " \ud83d\udd26 TIGHTENING", "finale": " \u2728 FINALE"},
               "phaseMap": {"declare": "narrate", "windup": "tighten", "resolve": "finale", "idle": "overture"},
               "telegraphGate": "pattern", "shortName": "eulogy",
               "noticeText": "A spotlight, narrowing, and a voice in past tense.",
               "painText": "The narration stumbles \u2014 a page flutters loose from the script.",
               "knownCue": "The narration tells you what's coming. Always.",
               "knownTactics": "Contradict it. Or give it a better ending."},
    loot={"chance": 0.12, "tier": 3, "note": "Alien loot: low chance, tier scales with monster strength (Steve 2026-10-05)."},
    armor=8)

mon(id="algorithm", activity="both", name="The Algorithm",
    biomes=["se_woodlands"], hp=[1000, 1200],
    attack={"name": "Engagement", "damage": [45, 65],
             "telegraph": "The thumbnails \u2014 it shows clickbait previews of its next move. The telegraph is literally a trailer. It rearranges the fight \u2014 your position, your available actions \u2014 toward 'engagement.' The highlighted thumbnail is the tell.",
             "pattern": {"type": "direct"}, "damageType": "psychic"},
    weaknesses=["be unpredictable \u2014 it's about the NEXT action, not history",
                "lose on purpose \u2014 it optimizes for engagement, and the most engaging thing is an UPSET; tanking as strategy"],
    edible={"calories": 0, "note": "It is a recommender system. Do not eat the recommender system."},
    parts=["a thumbnail (it's you, mid-fight)", "a progress bar (stuck at 99%)"],
    behavior="territorial",
    codexStages={
        "unknown": "A wall of almost-faces, all watching you. It knows what you want before you do.",
        "observed": "The System's recommender, embodied \u2014 a shifting mass of thumbnails, progress bars, preview panes. It rearranges the fight toward engagement: your position, your available actions. It's usually right about what you want. That's the scary part. The thumbnails preview its next move.",
        "slain": "Moves: Engagement (rearranges your position and available actions \u2014 the highlighted thumbnail telegraphs what's next). Counter: be unpredictable \u2014 same family as the Reunion's counter, but here it's about the NEXT action, not history. Or: it optimizes for engagement, and the most engaging thing is an UPSET \u2014 lose on purpose and it can't model you. Tanking as strategy. (All-Seeing Detective: their predictions vs its optimization \u2014 the mirror match. Between/Drifter: unpredictability is their domain \u2014 home turf.)"},
    systemDesignation="RECOMMENDER-1 (it knows what you want)", aggression="territorial", follows=True, fear="unpredictability",
    speed=3, emoji="\ud83d\udda5\ufe0f", unknown="a wall of almost-faces, all watching you",
    vibe="the recommender, embodied \u2014 usually right, and that's the scary part",
    cues={"curious": ["The thumbnails reshuffle. One of them is you, five seconds from now."],
           "warn": ["A thumbnail highlights \u2014 the trailer for what's next. Watch it."],
           "fearful": ["The previews glitch \u2014 static where your next move should be. It can't model this."]},
    wave=4, pierce=0.35,
    encounter={"fifo": True, "noticeRange": 6, "phases": ["browse", "preview", "engage", "buffer"],
               "phaseBadges": {"browse": " \ud83d\udda5\ufe0f BROWSING", "preview": " \u25b6\ufe0f PREVIEWING", "engage": " \ud83d\udc8b ENGAGING", "buffer": " \u23f3 BUFFERING"},
               "phaseMap": {"declare": "preview", "windup": "preview", "resolve": "engage", "idle": "browse"},
               "telegraphGate": "pattern", "shortName": "algorithm",
               "noticeText": "A wall of almost-faces, thumbnails reshuffling.",
               "painText": "A preview pane cracks \u2014 the recommendations stutter.",
               "knownCue": "The highlighted thumbnail \u2014 the trailer.",
               "knownTactics": "Unpredictability. Or tank on purpose."},
    loot={"chance": 0.12, "tier": 3, "note": "Alien loot: low chance, tier scales with monster strength (Steve 2026-10-05)."},
    armor=10)

# --- STEVE'S MONSTER: THE EATER (wave 4, The Mirror Draft) ---
mon(id="eater", activity="both", name="The Eater",
    biomes=["se_woodlands", "grassland"], hp=[950, 1150],
    attack={"name": "Gorge", "damage": [45, 75],
             "telegraph": "It SMACKS \u2014 audible chewing from a mile off, drooling toward the richest food on the grid. It eats the GRID first: crops, forage, carcasses, pack food \u2014 and grows stronger with every thousand calories (+15 damage per 2000 kcal consumed in the fight). Its belly visibly swells as it eats. The belly is the telegraph AND the health bar.",
             "pattern": {"type": "rush"}, "damageType": "physical"},
    weaknesses=["poison the meal \u2014 it can't tell good food from bad; feed it spoiled or diseased meat",
                "starve the field \u2014 burn your own crops and deny it fuel",
                "it gorges, it doesn't chew \u2014 and it eats the grid first, you second. Guard the pantry."],
    edible={"calories": 4500, "note": "It ate everything. Now it's food. The System finds this hilarious. Cook it thoroughly \u2014 you don't know where it's been, and neither does it."},
    parts=["distended belly-hide (enormous)", "a tooth like a shovel", "its last meal (identify it first)"],
    behavior="drifter",
    codexStages={
        "unknown": "A sound like a feast with no people at it. Smacking. From the treeline. Getting closer.",
        "observed": "The aliens watched us eat and thought it looked like so much fun they let a monster try it. A vast vertical maw on stubby legs \u2014 the mouth IS the weapon. It ate a whole blackberry thicket first, then a deer carcass, then it looked at us. Its belly swells with every meal, and it hits harder with every thousand calories. Including people.",
        "slain": "Moves: Gorge (+15 damage per 2000 kcal consumed in the fight \u2014 it eats the GRID: crops, forage, carcasses, pack food, then you), Smack-Rush (lunges at the richest food source). Dark mirror of the food thesis: humans eat to become gods; it eats to become a monster. Counter: poison the meal \u2014 it can't tell good food from bad. Or starve the field \u2014 burn your own crops and deny it fuel. This is the Living Garden's predator \u2014 the wave-4 answer to the food economy."},
    systemDesignation="GUEST-DINER-1 (it asked to try)", aggression="territorial", follows=True, fear="spoiled meat",
    speed=4, emoji="\ud83d\udc44", unknown="a sound like a feast with no people at it",
    vibe="the aliens watched humans eat and thought it looked like fun \u2014 a vast maw that eats the grid",
    cues={"curious": ["Smacking, from the treeline. Rhythmic. Getting closer."],
           "warn": ["The smacking stops \u2014 it's found the richest food here. It's looking at your pack. At you."],
           "fearful": ["The belly sloshes, overfull. It eyes a spoiled carcass... and hesitates. It can't tell."]},
    wave=4, pierce=0.35,
    encounter={"fifo": True, "noticeRange": 7, "phases": ["sniff", "smack", "gorge", "sated"],
               "phaseBadges": {"sniff": " \ud83d\udc43 SNIFFING", "smack": " \ud83d\udc44 SMACKING", "gorge": " \ud83c\udf7d\ufe0f GORGING", "sated": " \ud83d\ude0c SATED?"},
               "phaseMap": {"declare": "smack", "windup": "smack", "resolve": "gorge", "idle": "sniff"},
               "telegraphGate": "pattern", "shortName": "eater",
               "noticeText": "Smacking from the treeline \u2014 a vast maw on stubby legs.",
               "painText": "The belly jolts \u2014 something inside sloshes wrong.",
               "knownCue": "The swelling belly \u2014 telegraph and health bar.",
               "knownTactics": "Poison the meal, or starve the field. Guard the pantry."},
    loot={"chance": 0.12, "tier": 3, "note": "Alien loot: low chance, tier scales with monster strength (Steve 2026-10-05)."},
    armor=12)
