#!/usr/bin/env python3
# gen-wave35-data-20261010.py — one-shot: appends the 26 wave-3/4/5 monsters
# (25 draft + THE EATER) to src/data/monsters.json via byte-splice (no rewrite
# of existing entries — the file mixes escaped/raw unicode styles).
# Bands ANCHORED to sim-dps-anchor-20261010.js (seeds 1-3):
#   godhood brawler ~220/round, godhood hunter ~230/round, mid build ~64/round.
#   wave-5 HP = 220 x target rounds (apex 7-10, others 5-7); wave-4 = 220 x 4-6;
#   wave-3 = 64 x 4-6 (mid-build fight). Damage/pierce bands kept from the
#   draft — validated against sims (w5 vs P=138: 8-21/round, matches draft math).
import json, io, sys

M = []

def mon(**kw):
    M.append(kw)

# ================= WAVE 3 — THE FINAL DRAFT =================
mon(id="redactor", activity="nocturnal", name="The Redactor",
    biomes=["se_woodlands"], hp=[260, 320],
    attack={"name": "Redact", "damage": [35, 55],
             "telegraph": "Its white edge-handles grab toward you \u2014 pointing. Whatever it points at goes quiet. The handles ARE the telegraph.",
             "pattern": {"type": "direct"}, "damageType": "psychic"},
    weaknesses=["it redacts the loudest thing first \u2014 carry a decoy",
                "go quiet for two turns and it starves",
                "the handles point before it redacts \u2014 watch them, not the bar"],
    edible={"calories": 0, "note": "It is a redaction. Do not eat the redaction."},
    parts=["a strip of black bar (lightless)", "white handle-fragments (they point at you)"],
    behavior="ambush",
    codexStages={
        "unknown": "A missing piece of the world, shaped like a doorway. The trees behind it don't line up.",
        "observed": "A hovering black rectangle with white selection-handles, like a text cursor. It pointed at Mara's spear and the spear... wasn't, for two turns. The handles grab before it redacts \u2014 that grab is the only warning.",
        "slain": "Moves: Redact (silences one equipped item or ability for 2 turns \u2014 the handles point first, always), Return (redacted things come back. Probably). It redacts what you RELY on. Counter: go quiet \u2014 fight two turns with nothing but your hands and it starves. Or carry decoys: it redacts the loudest thing first."},
    systemDesignation="CENSOR-9 (field unit)", aggression="ambush", follows=True, fear="decoys",
    speed=3, emoji="\u2b1b", unknown="a missing piece of the world",
    vibe="censorship made flesh \u2014 polite, total, already editing you",
    cues={"curious": ["The black bar drifts closer. A handle twitches toward your pack."],
           "warn": ["Both handles grab toward you. Something you rely on is about to go quiet."],
           "fearful": ["The bar thins, flickers \u2014 nothing left loud enough to redact. It is starving."]},
    wave=3, pierce=0.1,
    encounter={"fifo": True, "noticeRange": 5, "phases": ["drift", "point", "redact", "return"],
               "phaseBadges": {"drift": " \u2b1b DRIFTING", "point": " \ud83d\udc49 POINTING", "redact": " \u2b1b REDACTING", "return": " \u21a9\ufe0f RETURNING"},
               "phaseMap": {"declare": "point", "windup": "point", "resolve": "redact", "idle": "drift"},
               "telegraphGate": "pattern", "shortName": "redactor",
               "noticeText": "A doorway-shaped hole in the world, drifting closer.",
               "painText": "The bar glitches \u2014 a frame of the world shows through the black.",
               "knownCue": "The handles point before it redacts. Always.",
               "knownTactics": "It redacts the loudest thing first. Go quiet or bring decoys."},
    loot={"chance": 0.15, "tier": 2, "note": "Alien loot: low chance, tier scales with monster strength (Steve 2026-10-05)."},
    armor=5)

mon(id="gavel", activity="diurnal", name="Gavel",
    biomes=["se_woodlands"], hp=[300, 360],
    attack={"name": "Verdict", "damage": [40, 60],
             "telegraph": "It raises the gavel-head high. The sound-block swings forward as a shield. It names your crime first \u2014 a full round before the verdict falls.",
             "pattern": {"type": "direct"}, "damageType": "physical"},
    weaknesses=["it is bound by procedure \u2014 object, cite precedent, demand a recess",
                "flank it \u2014 frontal attacks hit the sound-block",
                "confess first: smaller hit, but witnesses remember the confession"],
    edible={"calories": 0, "note": "It is a courthouse. Do not eat the courthouse."},
    parts=["gavel-splinters (heavy)", "the sound-block (dented, still rings)"],
    behavior="territorial",
    codexStages={
        "unknown": "A walking courthouse. You can hear the gavel before you see it, and you have done things.",
        "observed": "A car-sized gavel head on jointed legs, carrying its sound-block as a shield. It accused Joren \u2014 of something he actually did, on camera, three days ago. The accusation comes a full round before the verdict. Frontal attacks hit the block.",
        "slain": "Moves: Accusation (names a real logged action \u2014 telegraphed a full round ahead), Verdict (the gavel falls). Counter: it's bound by procedure. Object. Cite precedent. Demand a recess. Treat it like court, not a fight \u2014 the trial has rules and the rules bind IT too. Or confess first: smaller hit, but witnesses remember."},
    systemDesignation="JUDICIAL-4 (accountability content)", aggression="territorial", follows=False, fear="recess",
    speed=2, emoji="\u2696\ufe0f", unknown="a walking courthouse",
    vibe="the audience voted for accountability, and the System complied with unusual enthusiasm",
    cues={"curious": ["The gavel-head tilts. It is reviewing footage of you."],
           "warn": ["\"THE ACCUSED WILL RISE.\" It names what you did. Everyone hears."],
           "fearful": ["The gavel lowers. \"RECESS.\" It backs off, procedural to the end."]},
    wave=3, pierce=0.2,
    encounter={"fifo": True, "noticeRange": 5, "phases": ["docket", "accuse", "verdict", "adjourn"],
               "phaseBadges": {"docket": " \ud83d\udccb DOCKET", "accuse": " \u2696\ufe0f ACCUSING", "verdict": " \ud83d\udd28 VERDICT", "adjourn": " \ud83d\udcdc ADJOURNED"},
               "phaseMap": {"declare": "accuse", "windup": "accuse", "resolve": "verdict", "idle": "docket"},
               "telegraphGate": "pattern", "shortName": "gavel",
               "noticeText": "A courthouse on legs, reviewing your footage.",
               "painText": "A crack runs down the gavel-head. \"OBJECTION SUSTAINED,\" it mutters.",
               "knownCue": "The accusation comes a full round before the verdict.",
               "knownTactics": "Flank it \u2014 the sound-block only guards the front. Procedure binds it."},
    loot={"chance": 0.15, "tier": 3, "note": "Alien loot: low chance, tier scales with monster strength (Steve 2026-10-05)."},
    armor=8)

mon(id="focus_group", activity="both", name="The Focus Group",
    biomes=["se_woodlands"], hp=[240, 300],
    attack={"name": "Deliberation", "damage": [30, 45],
             "telegraph": "The murmur rises \u2014 you can HEAR them deliberating. They're about to love your dodge and hate your strike. The ratings are honest and visible.",
             "pattern": {"type": "burst"}, "damageType": "psychic"},
    weaknesses=["be deliberately boring for three rounds and they lose interest and LEAVE",
                "kill the mouth-heads first \u2014 eye-heads only mark you",
                "knowing what they'll rate IS the counter"],
    edible={"calories": 0, "note": "It is an audience. Do not eat the audience."},
    parts=["a mouth-head's teeth (still rating)", "an eye-head's lens (it watched you)"],
    behavior="swarm",
    codexStages={
        "unknown": "A committee that hasn't decided about you yet. The murmur follows you through the trees.",
        "observed": "Five to seven floating heads, each with one exaggerated feature. Mouth-heads bite; eye-heads mark you \u2014 marked actions get rated harder. You can hear the murmur before they act: they're about to love your dodge and hate your strike. Next round, dodge is buffed, strike is suppressed.",
        "slain": "Moves: Deliberation (audible telegraph \u2014 the ratings are honest), the System buffs what entertains them and suppresses what bores them. Shared HP \u2014 kill the mouth-heads first. Counter: be deliberately boring. Do nothing flashy for three rounds and they lose interest and LEAVE. The win is refusing to be content. (One-Person Army: rage is VERY entertaining \u2014 they will never leave a brawler.)"},
    systemDesignation="AUDIENCE-ID-7 (given bodies and a budget)", aggression="territorial", follows=True, fear="boredom",
    speed=3, emoji="\ud83d\udc65", unknown="a committee that hasn't decided about you yet",
    vibe="the audience's id, rating your every move out loud",
    cues={"curious": ["The murmur shifts. \"Ooh, a new one. Show us something.\""],
           "warn": ["The mouth-heads lean in. The murmur gets excited. This will be rated."],
           "fearful": ["The murmur thins... wanders... \"Next.\" They're leaving. Stay boring."]},
    wave=3, pierce=0.0,
    encounter={"fifo": True, "noticeRange": 6, "phases": ["murmur", "rate", "deliberate", "bored"],
               "phaseBadges": {"murmur": " \ud83d\udc65 MURMURING", "rate": " \u2b50 RATING", "deliberate": " \ud83d\udde3\ufe0f DELIBERATING", "bored": " \ud83e\udd71 BORED"},
               "phaseMap": {"declare": "deliberate", "windup": "deliberate", "resolve": "rate", "idle": "murmur"},
               "telegraphGate": "pattern", "shortName": "focus group",
               "noticeText": "Floating heads, mid-argument about you.",
               "painText": "A mouth-head pops like a soap bubble. The murmur dips.",
               "knownCue": "You can hear the deliberation \u2014 the ratings are honest.",
               "knownTactics": "Boring for three rounds and they leave. Mouth-heads first."},
    loot={"chance": 0.15, "tier": 2, "note": "Alien loot: low chance, tier scales with monster strength (Steve 2026-10-05)."},
    armor=4)

mon(id="spool", activity="nocturnal", name="Spool",
    biomes=["se_woodlands"], hp=[280, 340],
    attack={"name": "Replay", "damage": [35, 50],
             "telegraph": "RECORD first \u2014 harmless, it watches. Then REPLAY: the reels on its back spin, and the spinning reel SHOWS what's loaded. Watch the reel, not the tape.",
             "pattern": {"type": "direct"}, "damageType": "physical"},
    weaknesses=["spend three turns doing harmless things \u2014 eat, wait, talk to yourself \u2014 and the replay is useless",
                "feed it a heal: the replay heals YOU",
                "the reels show what's coming \u2014 read them"],
    edible={"calories": 0, "note": "It is a blooper reel. Do not eat the blooper reel."},
    parts=["a reel of tape (your fight is on it)", "magnetic tape (limbs, tangled)"],
    behavior="curious",
    codexStages={
        "unknown": "A tangle of tape that moves like it's remembering. It watched you for a while before you noticed.",
        "observed": "The System's blooper reel, weaponized. Visible film reels across its back; magnetic tape for limbs. It records your last 3 turns, then replays them AT you \u2014 your own numbers, echoed, capped. The spinning reel shows what's loaded.",
        "slain": "Moves: Record (harmless \u2014 it watches), Replay (your echoed actions, telegraphed by the reels). Counter: spend three turns doing harmless things and the replay is useless. Or feed it a heal \u2014 the replay heals YOU. (Apex Predator: their dead-aim spikes get replayed \u2014 the build's best moment becomes incoming.)"},
    systemDesignation="POST-PROD-2 (someone got a monster budget)", aggression="territorial", follows=True, fear="dead air",
    speed=3, emoji="\ud83c\udf9e\ufe0f", unknown="a tangle of tape that moves like it's remembering",
    vibe="your own blooper reel, and it's been saving the good stuff",
    cues={"curious": ["The reels turn slowly. It's watching. Recording."],
           "warn": ["The reels spin up \u2014 fast. Something you did is about to come back."],
           "fearful": ["The tape goes slack. Nothing worth replaying. It's losing interest."]},
    wave=3, pierce=0.15,
    encounter={"fifo": True, "noticeRange": 5, "phases": ["record", "rewind", "replay", "tangle"],
               "phaseBadges": {"record": " \ud83d\udcfa RECORDING", "rewind": " \u23ea REWINDING", "replay": " \u25b6\ufe0f REPLAYING", "tangle": " \ud83e\udea2 TANGLED"},
               "phaseMap": {"declare": "rewind", "windup": "rewind", "resolve": "replay", "idle": "record"},
               "telegraphGate": "pattern", "shortName": "spool",
               "noticeText": "Tape-limbs, reels turning, watching you.",
               "painText": "Tape snaps and whips loose. The reel wobbles.",
               "knownCue": "The spinning reel shows what's loaded.",
               "knownTactics": "Harmless turns make harmless replays. A fed heal heals you."},
    loot={"chance": 0.15, "tier": 2, "note": "Alien loot: low chance, tier scales with monster strength (Steve 2026-10-05)."},
    armor=5)

mon(id="chorus_line", activity="crepuscular", name="Chorus Line",
    biomes=["grassland", "se_woodlands"], hp=[300, 360],
    attack={"name": "Downbeat", "damage": [30, 48],
             "telegraph": "The music starts \u2014 an actual audio cue, 4/4, and you can feel the downbeat coming. The downbeat is the kick. Deafness breaks the telegraph but not the beat.",
             "pattern": {"type": "burst"}, "damageType": "physical"},
    weaknesses=["move ON the beat: dodge. Move OFF it: eat the kick",
                "dance \u2014 match the rhythm and you're untouchable",
                "throw something arrhythmic (a handful of gravel works)",
                "it can't turn fast \u2014 attack from the side"],
    edible={"calories": 0, "note": "It is a musical episode. Do not eat the musical episode."},
    parts=["a dancer's shoe (enormous)", "sheet music (4/4, aggressive)"],
    behavior="territorial",
    codexStages={
        "unknown": "A kickline with no music you can hear. Yet. The legs go all the way up.",
        "observed": "Synchronized AoE on a 4/4 beat \u2014 sweeps week, and the System is doing it anyway. Extremely long legs; the LINE formation is the tell \u2014 it can't turn fast, so flanking works. The downbeat is the hit, and you can hear it coming.",
        "slain": "Moves: Downbeat (AoE kick on the 4 \u2014 the music is the telegraph). Counter: dance. Match the rhythm \u2014 a real timing choice each round \u2014 and you're untouchable. Or break the rhythm: throw something arrhythmic. Deafness (or earplugs) breaks the telegraph but not the beat \u2014 the beat doesn't care about your HP pool, only your timing."},
    systemDesignation="SWEEPS-EP-12 (the System is not proud of this one)", aggression="territorial", follows=True, fear="silence",
    speed=4, emoji="\ud83d\udc83", unknown="a kickline with no music you can hear. Yet.",
    vibe="sweeps week \u2014 extremely long legs, extremely committed",
    cues={"curious": ["A toe taps. Four beats. It's counting you in."],
           "warn": ["The line straightens. The music swells. ONE two three\u2014"],
           "fearful": ["The kicks slow... stumble... the line breaks formation."]},
    wave=3, pierce=0.1,
    encounter={"fifo": True, "noticeRange": 6, "phases": ["countin", "downbeat", "kickline", "bow"],
               "phaseBadges": {"countin": " \ud83c\udfb5 COUNT-IN", "downbeat": " \ud83e\udd81 DOWNBEAT", "kickline": " \ud83d\udc83 KICKLINE", "bow": " \ud83d\ude47 BOW"},
               "phaseMap": {"declare": "countin", "windup": "downbeat", "resolve": "kickline", "idle": "countin"},
               "telegraphGate": "pattern", "shortName": "chorus line",
               "noticeText": "A kickline, mid-formation, in perfect time.",
               "painText": "A dancer stumbles \u2014 the line wobbles, the beat skips.",
               "knownCue": "The music \u2014 the downbeat is the hit.",
               "knownTactics": "Dance on the beat, or break the rhythm. Flank the line."},
    loot={"chance": 0.15, "tier": 2, "note": "Alien loot: low chance, tier scales with monster strength (Steve 2026-10-05)."},
    armor=6)

mon(id="terms_of_service", activity="both", name="The Terms of Service",
    biomes=["se_woodlands"], hp=[340, 420],
    attack={"name": "Clause", "damage": [25, 40],
             "telegraph": "The text on the scroll GLOWS before a clause activates \u2014 the glow runs along the words like a fuse. The telegraph is literally legible. Reading is the defense.",
             "pattern": {"type": "single"}, "damageType": "psychic"},
    weaknesses=["READ IT \u2014 spend turns examining and you'll find the loophole clause that dismisses it",
                "object now at small cost, or accept and pay bigger later \u2014 a real choice each clause",
                "it unrolls toward you \u2014 don't let it surround you"],
    edible={"calories": 0, "note": "It is a legal document. Do not eat the legal document."},
    parts=["a glowing clause (still binding?)", "paper \u2014 so much paper"],
    behavior="passive",
    codexStages={
        "unknown": "Fine print, approaching. It unrolls toward you. You feel like you've already agreed to something.",
        "observed": "A towering scroll that adds clauses mid-fight \u2014 'by standing here you agree...' Each clause is a debuff you accepted by not objecting in time. The text GLOWS before a clause activates; the glow runs like a fuse. Paper, mostly \u2014 but the paper is everywhere.",
        "slain": "Moves: Clause (debuff you accepted by not objecting \u2014 object now at small cost, or accept and pay bigger later). Counter: READ IT. Spend turns examining \u2014 knowledge as a weapon, literally \u2014 and you'll find the loophole clause that dismisses it. (Detective: this is their boss fight. Market God: they LIVE in fine print \u2014 home turf.)"},
    systemDesignation="LEGAL-1 (nobody is happy about this, including the System)", aggression="territorial", follows=False, fear="loopholes",
    speed=1, emoji="\ud83d\udcdc", unknown="fine print, approaching",
    vibe="the System's lawyers got a monster budget, and the paper is everywhere",
    cues={"curious": ["The scroll unrolls a little further. Small text. Smaller intentions."],
           "warn": ["A paragraph begins to glow. Read it. READ IT."],
           "fearful": ["The glow gutters. A loophole, found. The paper sags."]},
    wave=3, pierce=0.2,
    encounter={"fifo": True, "noticeRange": 5, "phases": ["preamble", "glow", "clause", "addendum"],
               "phaseBadges": {"preamble": " \ud83d\udcdc PREAMBLE", "glow": " \u2728 GLOWING", "clause": " \ud83d\udcdd CLAUSE", "addendum": " \ud83d\udcce ADDENDUM"},
               "phaseMap": {"declare": "glow", "windup": "glow", "resolve": "clause", "idle": "preamble"},
               "telegraphGate": "pattern", "shortName": "terms",
               "noticeText": "A towering scroll, unrolling toward you.",
               "painText": "The paper tears along a fold. The glow flickers.",
               "knownCue": "The text glows before a clause activates \u2014 legible.",
               "knownTactics": "Examine it \u2014 the loophole dismisses it. Object early."},
    loot={"chance": 0.15, "tier": 3, "note": "Alien loot: low chance, tier scales with monster strength (Steve 2026-10-05)."},
    armor=4)

mon(id="callback", activity="nocturnal", name="The Callback",
    biomes=["se_woodlands"], hp=[260, 320],
    attack={"name": "Encore", "damage": [30, 50],
             "telegraph": "It speaks \u2014 in their voice, saying things they said. The face is too symmetrical. The eyes don't track. The wrongness is the telegraph.",
             "pattern": {"type": "direct"}, "damageType": "psychic"},
    weaknesses=["the funeral \u2014 speak to it AS the person, say goodbye properly, and it loses coherence",
                "name it as NOT them \u2014 the village's naming debate as combat",
                "noticing the wrongness is the knowledge gate \u2014 look at the eyes"],
    edible={"calories": 0, "note": "It is grief. Do not eat grief."},
    parts=["a face that isn't theirs (it comes off like a mask)"],
    behavior="ambush",
    codexStages={
        "unknown": "Someone you know, walking wrong. You know the walk. The walk is wrong.",
        "observed": "It wears the face and voice of one of your dead \u2014 drawn from your actual dead, your broadcast history. It doesn't attack your HP first; it attacks your willingness to fight it. The face is too symmetrical. The eyes don't track. Noticing the wrongness is the knowledge gate.",
        "slain": "Moves: Encore (grief as a weapon \u2014 trauma/morale first, HP second). Counter: the funeral. Speak to it AS the person. Say goodbye properly \u2014 a real beat \u2014 and it loses coherence. Or: the village collectively names it as NOT them \u2014 the naming-debate mechanic as combat. (Shepherd of the Dead: this is their shadow.)"},
    systemDesignation="CLIP-SHOW-3 (mined from your footage)", aggression="ambush", follows=True, fear="farewells",
    speed=3, emoji="\ud83d\udc64", unknown="someone you know, walking wrong",
    vibe="the family thread, weaponized \u2014 it knows what makes you hesitate",
    cues={"curious": ["\"Hey,\" it says, in their voice. \"It's me.\" It is not."],
           "warn": ["The face smiles wrong. The eyes don't track. It's about to do the thing they used to do."],
           "fearful": ["\"Goodbye,\" you say, and mean it. The face loosens. It's losing coherence."]},
    wave=3, pierce=0.25,
    encounter={"fifo": True, "noticeRange": 5, "phases": ["approach", "speak", "encore", "falter"],
               "phaseBadges": {"approach": " \ud83d\udc64 APPROACHING", "speak": " \ud83d\udde3\ufe0f SPEAKING", "encore": " \ud83c\udfad ENCORE", "falter": " \ud83d\ude36 FALTERING"},
               "phaseMap": {"declare": "speak", "windup": "speak", "resolve": "encore", "idle": "approach"},
               "telegraphGate": "pattern", "shortName": "callback",
               "noticeText": "Someone you know, walking wrong, coming closer.",
               "painText": "The face slips \u2014 for a second it's just... wrong, and everyone sees it.",
               "knownCue": "The wrongness: too symmetrical, eyes don't track.",
               "knownTactics": "Say goodbye properly. Or name it as NOT them."},
    loot={"chance": 0.15, "tier": 2, "note": "Alien loot: low chance, tier scales with monster strength (Steve 2026-10-05)."},
    armor=3)

mon(id="buffering", activity="both", name="Buffering",
    biomes=["se_woodlands"], hp=[280, 340],
    attack={"name": "Catch Up", "damage": [40, 60],
             "telegraph": "Its telegraphs describe the FUTURE \u2014 'it will step left.' Afterimages trail it; the faintest frame is the real present. You must pre-dodge \u2014 or stop predicting entirely.",
             "pattern": {"type": "ambush"}, "damageType": "physical"},
    weaknesses=["stop predicting \u2014 close your eyes and swing at where it IS, not the projection",
                "stand perfectly still \u2014 it aims at your future position, and your future position is HERE",
                "the faintest frame is the real one"],
    edible={"calories": 0, "note": "It is a compression artifact. Do not eat the compression artifact."},
    parts=["a hung frame (it stutters in your pack)", "afterimage residue (faint, cold)"],
    behavior="drifter",
    codexStages={
        "unknown": "A stutter in the world. Frames of something hang in the air where nothing is.",
        "observed": "It exists 3 seconds in the past. You hit where it was; it hits where you WILL be \u2014 the System's stream delay, embodied. It stutters: frames hang in the air. The faintest frame is the one that's really there. Its telegraphs describe the future.",
        "slain": "Moves: Catch Up (strikes where you WILL be \u2014 pre-dodge, or don't move at all). Counter: stop predicting. Close your eyes and swing at where it IS. Or stand perfectly still \u2014 it aims at your future position, and your future position is HERE. (All-Seeing Detective: their prediction fantasy breaks \u2014 it lives in THEIR domain.)"},
    systemDesignation="STREAM-DELAY-1 (a compression artifact that achieved malice)", aggression="territorial", follows=True, fear="stillness",
    speed=5, emoji="\u23f3", unknown="a stutter in the world",
    vibe="three seconds ago, and angry about it",
    cues={"curious": ["A frame of it hangs in the air. Then another. It's buffering."],
           "warn": ["\"IT WILL STEP LEFT,\" the world says. The faintest frame twitches."],
           "fearful": ["The frames collapse into one \u2014 the present, caught. It's exposed."]},
    wave=3, pierce=0.2,
    encounter={"fifo": True, "noticeRange": 5, "phases": ["stutter", "afterimage", "catchup", "sync"],
               "phaseBadges": {"stutter": " \u23f3 STUTTERING", "afterimage": " \ud83d\udc65 AFTERIMAGE", "catchup": " \u23e9 CATCHING UP", "sync": " \ud83d\udd04 SYNCED"},
               "phaseMap": {"declare": "afterimage", "windup": "afterimage", "resolve": "catchup", "idle": "stutter"},
               "telegraphGate": "pattern", "shortName": "buffering",
               "noticeText": "Frames of something, hanging in empty air.",
               "painText": "A frame shatters \u2014 the past cracks, briefly.",
               "knownCue": "The faintest frame is the real present.",
               "knownTactics": "Attack the present, not the projection. Or don't move."},
    loot={"chance": 0.15, "tier": 2, "note": "Alien loot: low chance, tier scales with monster strength (Steve 2026-10-05)."},
    armor=4)

mon(id="ad_break", activity="both", name="Ad Break",
    biomes=["se_woodlands"], hp=[320, 380],
    attack={"name": "Sponsored Pause", "damage": [20, 35],
             "telegraph": "A giant floating AD glyph with a PROGRESS BAR \u2014 the bar is the telegraph. During the pause it repositions and heals, and you watch. After the bar fills, a 'skip ad' beat appears: skip faster if the audience likes you. Or look away \u2014 the ad's power is that you WATCH.",
             "pattern": {"type": "single"}, "damageType": "psychic"},
    weaknesses=["patience \u2014 wait for the skip beat",
                "look away \u2014 the ad's power is that you WATCH",
                "kill the sponsor-creature riding the glyph and the ad shortens"],
    edible={"calories": 0, "note": "It is sponsored content. Do not eat the sponsored content."},
    parts=["the sponsor-creature's smile (trophy)", "a fragment of progress bar"],
    behavior="passive",
    codexStages={
        "unknown": "An interruption with a progress bar. The fight... pauses. You're watching something.",
        "observed": "It pauses the fight for an ad \u2014 a giant AD glyph with a progress bar. During the pause it repositions and heals, and you watch. A small smiling sponsor-creature rides the glyph. The System apologizes for this one. The apology is also sponsored.",
        "slain": "Moves: Sponsored Pause (the fight stops; it repositions and heals). Counter, three ways, all lateral: patience (wait for the skip beat \u2014 faster if the audience likes you), inattention (look away), or murder the sponsor (kill the rider and the ad shortens). It's a pacing monster, not a build check. (Market God: they understand sponsors \u2014 home turf.)"},
    systemDesignation="INVENTORY-7 (the sponsors demanded inventory)", aggression="territorial", follows=False, fear="inattention",
    speed=1, emoji="\ud83d\udcfa", unknown="an interruption with a progress bar",
    vibe="the sponsors demanded inventory, and the System complied",
    cues={"curious": ["\"WE'LL BE RIGHT BACK,\" says the sky."],
           "warn": ["The AD glyph brightens. The progress bar starts filling. Don't watch. DON'T watch."],
           "fearful": ["\"SKIP AD\" \u2014 the bar completes, the glyph flickers out."]},
    wave=3, pierce=0.15,
    encounter={"fifo": True, "noticeRange": 6, "phases": ["preroll", "pause", "skip", "resume"],
               "phaseBadges": {"preroll": " \ud83d\udcfa PREROLL", "pause": " \u23f8\ufe0f PAUSED", "skip": " \u23ed SKIP?", "resume": " \u25b6\ufe0f RESUMED"},
               "phaseMap": {"declare": "preroll", "windup": "pause", "resolve": "pause", "idle": "resume"},
               "telegraphGate": "pattern", "shortName": "ad break",
               "noticeText": "The world holds up a progress bar. An ad is coming.",
               "painText": "The glyph glitches \u2014 the sponsor-creature winces.",
               "knownCue": "The progress bar \u2014 and the skip beat when it fills.",
               "knownTactics": "Look away, wait for skip, or kill the sponsor."},
    loot={"chance": 0.15, "tier": 2, "note": "Alien loot: low chance, tier scales with monster strength (Steve 2026-10-05)."},
    armor=6)
