#!/usr/bin/env python3
# gen-wave35-data-20261010.py — PART 3: wave 5 (The Producers).
# Continued from part1 (defines mon() and M).

# ================= WAVE 5 — THE PRODUCERS =================
mon(id="cancellation", activity="both", name="The Cancellation",
    biomes=["se_woodlands"], hp=[1600, 2000],
    attack={"name": "Under Review", "damage": [70, 100],
             "telegraph": "A giant STAMP descends slowly \u2014 the longest telegraph in the game. The ink is red. It doesn't fight you \u2014 it fights your EXISTENCE in the show: fans, codex entries, broadcast presence. Deletes buffs, un-teaches abilities temporarily ('under review'), silences System favor. You have time. Use it.",
             "pattern": {"type": "single"}, "damageType": "psychic"},
    weaknesses=["go off-script \u2014 it can only cancel what's IN the script; improvise (use abilities in ways never intended)",
                "spend audience favor \u2014 the audience can overrule a cancellation (renewal campaign as combat)",
                "the stamp is slow \u2014 you have time. Use it."],
    edible={"calories": 0, "note": "It is a standards department. Do not eat the standards department."},
    parts=["the red stamp (it still works. do not press it)", "your cancellation letter (framed?)"],
    behavior="territorial",
    codexStages={
        "unknown": "The sky, clearing its throat. A shadow like a stamp, very high up.",
        "observed": "The standards department finally lost patience. It doesn't fight you \u2014 it fights your existence in the show: fans turn, codex entries go 'under review', broadcast presence thins. Buffs get deleted; abilities get un-taught temporarily. The STAMP descends slowly \u2014 the longest telegraph in the game \u2014 and the ink is red.",
        "slain": "Moves: Under Review (un-teaching, buff deletion, favor silence \u2014 telegraphed by the slow red stamp). The anti-player monster. Counter: go off-script \u2014 it can only cancel what's IN the script; improvise, use abilities in ways never intended, and it can't file the paperwork. Or spend audience favor: the audience can overrule a cancellation \u2014 renewal campaign as combat. (EVERYONE is pressured \u2014 Shepherd especially; their echoes are the easiest thing to cancel.)"},
    systemDesignation="STANDARDS-1 (patience: exhausted)", aggression="territorial", follows=False, fear="improv",
    speed=1, emoji="\u274c", unknown="the sky, clearing its throat",
    vibe="bureaucracy at a geological scale \u2014 the show is fighting back",
    cues={"curious": ["The sky clears its throat. Ahem. Everyone looks up."],
           "warn": ["The STAMP descends \u2014 slowly, redly. You have time. Use it."],
           "fearful": ["The stamp hesitates \u2014 mid-air. That wasn't in the script. It can't file this."]},
    wave=5, pierce=0.6,
    encounter={"fifo": True, "noticeRange": 8, "phases": ["throatclear", "descend", "stamp", "filed"],
               "phaseBadges": {"throatclear": " \u26c5 CLEARING THROAT", "descend": " \ud83d\udcc9 DESCENDING", "stamp": " \u274c STAMPING", "filed": " \ud83d\uddc2\ufe0f FILED"},
               "phaseMap": {"declare": "descend", "windup": "descend", "resolve": "stamp", "idle": "throatclear"},
               "telegraphGate": "pattern", "shortName": "cancellation",
               "noticeText": "The sky clears its throat. A stamp-shaped shadow, very high.",
               "painText": "The stamp wobbles \u2014 red ink spatters the sky.",
               "knownCue": "The slow red stamp \u2014 the longest telegraph in the game.",
               "knownTactics": "Improvise \u2014 off-script can't be filed. Or spend favor."},
    loot={"chance": 0.10, "tier": 4, "note": "Alien loot: low chance, tier scales with monster strength (Steve 2026-10-05). Tier 4 earned through hardest challenges at low rates."},
    armor=16)

mon(id="editor", activity="nocturnal", name="The Editor",
    biomes=["se_woodlands"], hp=[1500, 1900],
    attack={"name": "Cut", "damage": [80, 110],
             "telegraph": "The scissors SNIP slowly \u2014 you hear it coming. It cuts things OUT: your last turn (redo it), your position (you're suddenly elsewhere), your ally ('left on the cutting-room floor' for 3 rounds). Film strips hang from it showing what's about to be cut \u2014 readable telegraph.",
             "pattern": {"type": "line"}, "damageType": "physical"},
    weaknesses=["the cutting-room floor \u2014 what's cut isn't GONE, it's somewhere; go back for them",
                "continuity errors \u2014 do two contradictory things and it can't cut cleanly"],
    edible={"calories": 0, "note": "It is post-production. Do not eat post-production."},
    parts=["a film strip (you're on it, mid-sentence)", "a snipped scene (take it back from the cutting-room floor)"],
    behavior="territorial",
    codexStages={
        "unknown": "Scissors, and the world getting shorter. The trees are closer together than they were.",
        "observed": "Tower-sized scissors; the film strips are the organs. Post-production, live: it cuts your last turn (redo it), your position (suddenly elsewhere), your ally \u2014 left on the cutting-room floor for 3 rounds. The scissors snip slowly; the film strips show what's about to be cut.",
        "slain": "Moves: Cut (excisions \u2014 turn, position, ally; telegraphed by the snip and the strips). Counter: the cutting-room floor \u2014 what's cut isn't GONE, it's somewhere; the counter is going back for them. Or continuity errors: do two contradictory things and it can't cut cleanly. (Between/Drifter: their whole thing is being elsewhere \u2014 the Editor does it TO you. Apex Predator: their positioning game, shredded.)"},
    systemDesignation="POST-PROD-9 (the director's cut, and you're not the director)", aggression="territorial", follows=True, fear="continuity errors",
    speed=3, emoji="\u2702\ufe0f", unknown="scissors, and the world getting shorter",
    vibe="the director's cut \u2014 and you're not the director",
    cues={"curious": ["Snip. ...Snip. The world gets slightly shorter."],
           "warn": ["The scissors open \u2014 slowly. The film strips show what's about to be cut."],
           "fearful": ["The blades jam \u2014 on a contradiction. It can't cut cleanly."]},
    wave=5, pierce=0.65,
    encounter={"fifo": True, "noticeRange": 6, "phases": ["assembly", "snip", "cut", "floor"],
               "phaseBadges": {"assembly": " \ud83c\udfac ASSEMBLY", "snip": " \u2702\ufe0f SNIPPING", "cut": " \u2716\ufe0f CUTTING", "floor": " \ud83d\udccb CUTTING-ROOM FLOOR"},
               "phaseMap": {"declare": "snip", "windup": "snip", "resolve": "cut", "idle": "assembly"},
               "telegraphGate": "pattern", "shortName": "editor",
               "noticeText": "Tower-sized scissors, film strips hanging like organs.",
               "painText": "A blade nicks \u2014 the snip stutters.",
               "knownCue": "The slow snip; the film strips show what's next.",
               "knownTactics": "Retrieve from the cutting-room floor. Contradict yourself."},
    loot={"chance": 0.10, "tier": 4, "note": "Alien loot: low chance, tier scales with monster strength (Steve 2026-10-05). Tier 4 earned through hardest challenges at low rates."},
    armor=18)

mon(id="rerun", activity="both", name="The Rerun",
    biomes=["se_woodlands"], hp=[1200, 1500],
    attack={"name": "Take Twelve", "damage": [60, 90],
             "telegraph": "A clapperboard \u2014 it CLAPS before a reset, and the take number increments. Every 5 rounds the fight RESTARTS: HP resets both sides, but IT remembers and you don't. You can count down. The number is always visible.",
             "pattern": {"type": "direct"}, "damageType": "psychic"},
    weaknesses=["leave messages for yourself \u2014 write in the journal/codex BETWEEN resets; writing persists",
                "win FAST \u2014 kill it within 5 rounds; a pure DPS check, the one place a stat check is honest",
                "between takes the set is visible \u2014 a brief vulnerability window"],
    edible={"calories": 0, "note": "It is a repeat broadcast. Do not eat the repeat broadcast."},
    parts=["the clapperboard (take 12)", "a studio light (hot, brief)"],
    behavior="territorial",
    codexStages={
        "unknown": "D\u00e9j\u00e0 vu with teeth. You've done this before. You haven't done this before.",
        "observed": "Every 5 rounds, the fight RESTARTS \u2014 HP resets both sides, but IT remembers and you don't. The episode airs again. A clapperboard claps before each reset; the take number increments, always visible. Between takes, the set is visible \u2014 and briefly vulnerable.",
        "slain": "Moves: Take Twelve (the reset \u2014 countdown via the clapperboard). Counter: leave messages for yourself \u2014 the knowledge system as weapon; write in the journal/codex BETWEEN resets, writing persists. Or win FAST: kill it within 5 rounds \u2014 a pure DPS check, the one place a stat check is honest. (Detective/All-Seeing: their knowledge persists \u2014 the intended counter. One-Person Army: the DPS race is their domain.)"},
    systemDesignation="PROGRAMMING-4 (the network ordered more episodes)", aggression="territorial", follows=True, fear="fast kills",
    speed=2, emoji="\ud83d\udd01", unknown="d\u00e9j\u00e0 vu with teeth",
    vibe="the network ordered more episodes \u2014 the episode airs again",
    cues={"curious": ["\"TAKE TWELVE,\" says the sky. You've heard this before."],
           "warn": ["The clapperboard rises. The take number increments. Count down."],
           "fearful": ["The clapperboard wobbles \u2014 the reset stutters. You're winning too fast."]},
    wave=5, pierce=0.5,
    encounter={"fifo": True, "noticeRange": 6, "phases": ["take", "clap", "reset", "air"],
               "phaseBadges": {"take": " \ud83c\udfac TAKE 12", "clap": " \ud83d\udc4f CLAP", "reset": " \ud83d\udd01 RESETTING", "air": " \ud83d\udcfa ON AIR"},
               "phaseMap": {"declare": "clap", "windup": "clap", "resolve": "reset", "idle": "take"},
               "telegraphGate": "pattern", "shortName": "rerun",
               "noticeText": "A clapperboard, and a feeling you've been here.",
               "painText": "The clapperboard cracks \u2014 take 13 will be late.",
               "knownCue": "The clap; the incrementing take number.",
               "knownTactics": "Write between resets. Or kill it in 5 rounds."},
    loot={"chance": 0.10, "tier": 3, "note": "Alien loot: low chance, tier scales with monster strength (Steve 2026-10-05)."},
    armor=14)

mon(id="spoiler", activity="both", name="The Spoiler",
    biomes=["se_woodlands"], hp=[1300, 1600],
    attack={"name": "Leaked Ending", "damage": [75, 105],
             "telegraph": "Trailer-voice announcements \u2014 the telegraph IS the announcement: it tells you how the fight ends, truthfully. Announced outcomes gain weight under the System (announced things happen). The poster changes to show the announced outcome. The honesty is the horror.",
             "pattern": {"type": "single"}, "damageType": "psychic"},
    weaknesses=["it must tell the truth \u2014 ask it the RIGHT question ('what happens if I do X?') and the answer binds IT too",
                "fulfill the spoiler on YOUR terms: it says you fall \u2014 fall PRONE, deliberately, and the prophecy is satisfied cheaply"],
    edible={"calories": 0, "note": "It is a trailer. Do not eat the trailer."},
    parts=["the key art (the ending, spoiled)", "a trailer script (it's all true)"],
    behavior="passive",
    codexStages={
        "unknown": "A voiceover that knows too much. The trailer told you everything. The trailer was right.",
        "observed": "No body \u2014 a voiceover with key art. The marketing department leaked the finale. It tells you how the fight ends \u2014 truthfully \u2014 and announced outcomes gain weight under the System: announced things happen. The poster changes to show the announced outcome.",
        "slain": "Moves: Leaked Ending (truthful announcements that gain weight \u2014 the announcement IS the telegraph). Counter: it must tell the truth \u2014 ask it the RIGHT question ('what happens if I do X?') and the answer binds IT too. Or fulfill the spoiler on YOUR terms: it says you fall \u2014 fall PRONE, deliberately, and the prophecy is satisfied cheaply. Undertale as hell. (Detective: truth as weapon \u2014 their arena. Eulogy veterans: same family, scaled up \u2014 Eulogy is the doom you INTERRUPT, Spoiler is the truth you EXPLOIT.)"},
    systemDesignation="MARKETING-2 (the trailer told you everything)", aggression="territorial", follows=False, fear="good questions",
    speed=1, emoji="\ud83d\udce2", unknown="a voiceover that knows too much",
    vibe="the marketing department leaked the finale \u2014 and it was right",
    cues={"curious": ["\"IN A WORLD...\" begins the voiceover. It's talking about you."],
           "warn": ["\"AND THEN THEY FELL.\" The poster changes. It's showing the ending."],
           "fearful": ["\"...UNLESS\u2014\" The voiceover falters. You asked the right question."]},
    wave=5, pierce=0.55,
    encounter={"fifo": True, "noticeRange": 7, "phases": ["teaser", "announce", "poster", "release"],
               "phaseBadges": {"teaser": " \ud83d\udce2 TEASER", "announce": " \ud83d\udce2 ANNOUNCING", "poster": " \ud83d\uddbc\ufe0f POSTER", "release": " \ud83c\udf9f\ufe0f RELEASE"},
               "phaseMap": {"declare": "announce", "windup": "announce", "resolve": "release", "idle": "teaser"},
               "telegraphGate": "pattern", "shortName": "spoiler",
               "noticeText": "A voiceover, and key art showing... you. Later.",
               "painText": "The key art tears \u2014 the ending smudges.",
               "knownCue": "The announcement \u2014 and the changing poster.",
               "knownTactics": "Ask binding questions. Fulfill prophecies cheaply."},
    loot={"chance": 0.10, "tier": 3, "note": "Alien loot: low chance, tier scales with monster strength (Steve 2026-10-05)."},
    armor=14)

mon(id="timeslot", activity="both", name="The Timeslot",
    biomes=["grassland", "se_woodlands"], hp=[1400, 1700],
    attack={"name": "Reschedule", "damage": [65, 95],
             "telegraph": "A giant TV guide \u2014 the highlighted slot shows where you're going next: worse and worse venues (a burning building, a wave-4 suburb, mid-air). Always readable, always in advance. Programming. Venues arrive with their own natives.",
             "pattern": {"type": "burst"}, "damageType": "physical"},
    weaknesses=["own the venue \u2014 every venue has a native; befriend it, or be FROM somewhere worse",
                "get bumped: be so boring the show moves you to a better slot"],
    edible={"calories": 0, "note": "It is a programming schedule. Do not eat the programming schedule."},
    parts=["the remote (one big red button \u2014 it never presses it)", "a TV guide (last week's, useless)"],
    behavior="drifter",
    codexStages={
        "unknown": "The ground, getting a new address. The trees look... scheduled.",
        "observed": "It moves the fight \u2014 reschedules you to worse and worse venues. A giant TV guide; the highlighted slot shows where you're going next, always readable, always in advance. The schedule changed. The schedule always changes. Venues arrive with their own natives.",
        "slain": "Moves: Reschedule (venue change + venue hazards \u2014 the guide telegraphs the next slot). Counter: own the venue \u2014 every venue has a native; befriend it, or be FROM somewhere worse. Or get bumped: be so boring the show moves you to a better slot (the Focus Group's counter, weaponized at wave 5). (Farstrider: venues are their domain. Unkillable: their game is enduring \u2014 the venues test exactly that.)"},
    systemDesignation="PROGRAMMING-1 (the schedule always changes)", aggression="territorial", follows=True, fear="boredom",
    speed=3, emoji="\ud83d\udcc5", unknown="the ground, getting a new address",
    vibe="programming \u2014 the schedule changed, and it's worse now",
    cues={"curious": ["The TV guide flips a page. Your slot is highlighted. It's not a good slot."],
           "warn": ["The highlighted slot blinks. The venue is changing. Hold onto something."],
           "fearful": ["The guide flips back \u2014 quickly. You're too boring for this slot."]},
    wave=5, pierce=0.5,
    encounter={"fifo": True, "noticeRange": 7, "phases": ["listing", "highlight", "reschedule", "bump"],
               "phaseBadges": {"listing": " \ud83d\udcc5 LISTING", "highlight": " \ud83d\udd26 HIGHLIGHTED", "reschedule": " \ud83d\udccd RESCHEDULING", "bump": " \ud83d\udcce BUMPED"},
               "phaseMap": {"declare": "highlight", "windup": "highlight", "resolve": "reschedule", "idle": "listing"},
               "telegraphGate": "pattern", "shortName": "timeslot",
               "noticeText": "A giant TV guide, pages turning by themselves.",
               "painText": "The guide tears \u2014 a page of venues flutters loose.",
               "knownCue": "The highlighted slot \u2014 always in advance.",
               "knownTactics": "Befriend the venue's natives. Or be boring."},
    loot={"chance": 0.10, "tier": 3, "note": "Alien loot: low chance, tier scales with monster strength (Steve 2026-10-05)."},
    armor=15)

mon(id="nielsen", activity="both", name="The Nielsen",
    biomes=["se_woodlands"], hp=[1100, 1400],
    attack={"name": "Sweeps Week", "damage": [50, 80],
             "telegraph": "The pupil DILATES before it acts. It doesn't attack \u2014 it WATCHES, and what it watches becomes real: its gaze buffs itself, and a visible viewer counter scales the fight's difficulty. Viewers arrive when you do flashy things. The counter is always visible \u2014 honest. You can watch the audience arrive.",
             "pattern": {"type": "single"}, "damageType": "psychic"},
    weaknesses=["FIGHT BORING \u2014 the smallest, dullest actions starve it of viewers; the epic win is refusing to be epic",
                "perform DELIBERATELY \u2014 if you must be watched, be watched on your terms"],
    edible={"calories": 0, "note": "It is ratings. Do not eat the ratings."},
    parts=["the remote (one big red button \u2014 the threat is enough)", "a viewer counter (stuck on your number)"],
    behavior="passive",
    codexStages={
        "unknown": "Being watched, physically. The air has a pupil in it.",
        "observed": "A single giant eye with a remote. Ratings, embodied \u2014 the most-watched thing in the room is you. It doesn't attack; it WATCHES, and what it watches becomes real: its gaze buffs itself, and a visible viewer counter scales the fight. Viewers arrive when you do flashy things. The remote has one big red button. It never presses it. The threat is enough.",
        "slain": "Moves: Sweeps Week (viewer-scaled difficulty \u2014 the counter is the telegraph; the pupil dilates before it acts). Counter, the most radical in the book: FIGHT BORING. The smallest, dullest actions starve it of viewers; the epic win is refusing to be epic. Or perform DELIBERATELY (the Influencer's lesson: if you must be watched, be watched on your terms). (One-Person Army: their rage is CONTENT \u2014 the Nielsen feasts. Shepherd: their growing party is a growing audience \u2014 the strength becomes the trap.)"},
    systemDesignation="RATINGS-1 (the most-watched thing in the room is you)", aggression="territorial", follows=False, fear="boredom",
    speed=1, emoji="\ud83d\udc41\ufe0f", unknown="being watched, physically",
    vibe="ratings, embodied \u2014 you can watch the audience arrive",
    cues={"curious": ["The eye opens. The viewer counter ticks up. Hello, audience."],
           "warn": ["The pupil dilates \u2014 the counter climbing. It's about to get real."],
           "fearful": ["The counter stalls... dips. The eye blinks, uncertain. Stay boring."]},
    wave=5, pierce=0.4,
    encounter={"fifo": True, "noticeRange": 8, "phases": ["watch", "dilate", "sweeps", "signoff"],
               "phaseBadges": {"watch": " \ud83d\udc41\ufe0f WATCHING", "dilate": " \ud83d\udd0d DILATING", "sweeps": " \ud83d\udcfa SWEEPS", "signoff": " \ud83d\udcbf SIGN-OFF"},
               "phaseMap": {"declare": "dilate", "windup": "dilate", "resolve": "sweeps", "idle": "watch"},
               "telegraphGate": "pattern", "shortName": "nielsen",
               "noticeText": "A giant eye, opening. A viewer counter, ticking up.",
               "painText": "The eye waters \u2014 the counter flickers.",
               "knownCue": "The dilating pupil; the honest viewer counter.",
               "knownTactics": "Fight boring. Starve it of viewers."},
    loot={"chance": 0.10, "tier": 3, "note": "Alien loot: low chance, tier scales with monster strength (Steve 2026-10-05)."},
    armor=12)

mon(id="finale", activity="both", name="The Finale",
    biomes=["se_woodlands"], hp=[1800, 2200],
    attack={"name": "Season Finale", "damage": [60, 85],
             "telegraph": "It GROWS every round \u2014 visible escalation, you can SEE the finale coming. Once per fight it declares a finale: a 3-round countdown to a massive UNAVOIDABLE strike [150,200] (the season finale). You can't dodge it. You feed it: sacrifice a thing \u2014 an item, an ability charge, a memory \u2014 and it passes. The countdown is diegetic ('previously on...' segments).",
             "pattern": {"type": "beam"}, "damageType": "physical"},
    weaknesses=["the sacrifice \u2014 WHAT will you feed it? (a real, painful choice \u2014 the game at its best)",
                "END IT FIRST \u2014 the DPS race, honest",
                "doom deaths trigger phoenix_clause normally \u2014 unkillable means unkillable"],
    edible={"calories": 0, "note": "It is a season finale. Do not eat the season finale."},
    parts=["the falling title card (dodge the rerun)", "a 'previously on...' segment (it's you)"],
    behavior="territorial",
    codexStages={
        "unknown": "The sky, getting bigger. It starts sky-sized and gets bigger.",
        "observed": "Every season needs its climax. This one is yours. It grows every round \u2014 scale as telegraph. Once per fight it declares a finale: 3 rounds to a massive unavoidable strike, and you can see it coming the whole time. The finale strike is a falling title card.",
        "slain": "Moves: Season Finale (normal strikes [60,85]; once per fight, a 3-round countdown to an UNAVOIDABLE [150,200] finale strike). Counter: the sacrifice \u2014 feed it a thing (an item, an ability charge, a memory) and it passes; WHAT will you feed it is a real, painful choice. Or END IT FIRST \u2014 the DPS race, honest again. Ruling, Steve: doom-countdown deaths trigger phoenix_clause the same as any death \u2014 unkillable means unkillable. (Unkillable: their whole fantasy vs the un-outlastable \u2014 the intended wall. Undying Ward: their 'no one dies' vs the finale \u2014 the cruelest matchup in the book.)"},
    systemDesignation="SEASON-FINALE (live)", aggression="territorial", follows=True, fear="cancellation",
    speed=2, emoji="\ud83c\udf0c", unknown="the sky, getting bigger",
    vibe="every season needs its climax \u2014 this one is yours",
    cues={"curious": ["\"PREVIOUSLY ON...\" The sky replays your life. It's been watching."],
           "warn": ["It grows \u2014 visibly. \"THE FINALE,\" says the sky. \"THREE ROUNDS.\""],
           "fearful": ["The growth stalls. The title card wavers, mid-fall. Feed it, or finish it."]},
    wave=5, pierce=0.75,
    encounter={"fifo": True, "noticeRange": 8, "phases": ["previously", "grow", "declare", "titlecard"],
               "phaseBadges": {"previously": " \ud83c\udf0c PREVIOUSLY", "grow": " \ud83d\udcc8 GROWING", "declare": " \ud83d\udce2 FINALE", "titlecard": " \ud83c\udfac TITLE CARD"},
               "phaseMap": {"declare": "declare", "windup": "declare", "resolve": "titlecard", "idle": "grow"},
               "telegraphGate": "pattern", "shortName": "finale",
               "noticeText": "The sky, getting bigger. 'Previously on...' \u2014 it's you.",
               "painText": "The title card cracks \u2014 the finale flickers.",
               "knownCue": "The growth; the 3-round 'previously on' countdown.",
               "knownTactics": "Feed it something painful, or end it first."},
    loot={"chance": 0.10, "tier": 4, "note": "Alien loot: low chance, tier scales with monster strength (Steve 2026-10-05). Tier 4 earned through hardest challenges at low rates."},
    armor=20)

mon(id="network_note", activity="diurnal", name="The Network Note",
    biomes=["se_woodlands"], hp=[1000, 1300],
    attack={"name": "Just Fix It", "damage": [55, 80],
             "telegraph": "The hovering memo's text is VISIBLE \u2014 you can read the incoming buff before it lands: 'the wolf should have lasers now' \u2014 and then it does. The pen underlines before the buff applies. (Knowledge-gating applies: you have to actually read it.) Mid-fight, it 'fixes' the other monsters. The executives are watching.",
             "pattern": {"type": "direct"}, "damageType": "psychic"},
    weaknesses=["kill it FIRST \u2014 it's support; the rare 'focus the buffoon' correct call",
                "give it BAD notes \u2014 it takes suggestions; plant a terrible idea ('the wolf should be SMALLER') and it 'fixes' the enemy into uselessness"],
    edible={"calories": 0, "note": "It is a memo. Do not eat the memo."},
    parts=["the red pen (it underlines)", "a memo ('the wolf should have lasers now' \u2014 it does)"],
    behavior="passive",
    codexStages={
        "unknown": "A memo, cc'd to the sky. The worst meeting you've ever been in, with teeth.",
        "observed": "It gives the System notes \u2014 LIVE. Mid-fight, it 'fixes' the other monsters, and the memo's text is visible: you can read the incoming buff before it lands, if you actually read it. The pen underlines before the buff applies.",
        "slain": "Moves: Just Fix It (buff aura for allies + direct damage \u2014 the memo telegraphs the buff). Counter: kill it FIRST \u2014 it's support; the rare 'focus the buffoon' correct call. Or give it BAD notes: it takes suggestions \u2014 plant a terrible idea ('the wolf should be smaller') and it 'fixes' the enemy into uselessness. Social engineering as combat. (Detective: their information game \u2014 the memo is readable. Everyone: it's a force multiplier \u2014 the priority target.)"},
    systemDesignation="EXEC-1 (the executives are watching)", aggression="territorial", follows=False, fear="bad ideas",
    speed=2, emoji="\ud83d\udcdd", unknown="a memo, cc'd to the sky",
    vibe="the worst meeting you've ever been in, with teeth \u2014 the executives are watching",
    cues={"curious": ["\"QUICK NOTE,\" says the memo. The pen hovers."],
           "warn": ["The pen underlines \u2014 twice. A buff is incoming. Read the memo."],
           "fearful": ["\"...REVERT THAT,\" says the memo, quickly. The pen shakes."]},
    wave=5, pierce=0.45,
    encounter={"fifo": True, "noticeRange": 6, "phases": ["cc", "underline", "fix", "revert"],
               "phaseBadges": {"cc": " \ud83d\udcdd CC'D", "underline": " \u2712\ufe0f UNDERLINING", "fix": " \ud83d\udd27 FIXING", "revert": " \u21a9\ufe0f REVERTING"},
               "phaseMap": {"declare": "underline", "windup": "underline", "resolve": "fix", "idle": "cc"},
               "telegraphGate": "pattern", "shortName": "network note",
               "noticeText": "A memo, hovering, cc'd to the sky.",
               "painText": "The memo crumples at the corner. \"NOTED.\"",
               "knownCue": "The visible memo text; the underlining pen.",
               "knownTactics": "Focus it first. Or feed it terrible ideas."},
    loot={"chance": 0.10, "tier": 3, "note": "Alien loot: low chance, tier scales with monster strength (Steve 2026-10-05)."},
    armor=12)
